let
    StartDate = #date(2021,1,1),
    NumberOfDays = Duration.Days( #date(2023,12,31) - StartDate ),
    Dates = List.Dates(StartDate, NumberOfDays+1, #duration(1,0,0,0)),
    #"Converted to Table" = Table.FromList(Dates, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table",{{"Column1", "Date"}}),
    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Date", type date}}),
    #"Inserted Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
    #"Inserted Month" = Table.AddColumn(#"Inserted Year", "Month", each Date.Month([Date]), Int64.Type),
    #"Inserted Month Name" = Table.AddColumn(#"Inserted Month", "Month Name", each Date.MonthName([Date], "en-us"), type text),
    #"Inserted Quarter" = Table.AddColumn(#"Inserted Month Name", "Quarter", each Date.QuarterOfYear([Date]), Int64.Type),
    #"Inserted Merged Column" = Table.AddColumn(#"Inserted Quarter", "MonthYear", each Text.Combine({[Month Name], Text.From([Year], "nl-NL")}, ", "), type text),
    #"Added Custom" = Table.AddColumn(#"Inserted Merged Column", "MonthKey", each [Year] * 100 + [Month]),
    #"Added Custom1" = Table.AddColumn(#"Added Custom", "QuarterYear", each "Q" & Text.From([Quarter]) & ", " & Text.From([Year])),
    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom1",{{"QuarterYear", type text}, {"MonthKey", Int64.Type}}),
    #"Renamed Columns1" = Table.RenameColumns(#"Changed Type1",{{"Month", "MonthNo"}})
in
    #"Renamed Columns1"